### PR TITLE
Gracefully handle authentication failure.

### PR DESCRIPTION
**Pull request by texpert**
This is to solve https://github.com/vassilevsky/face_control/issues/17

### CODE REVIEW

**Comment by vassilevsky** [comment]
Hi. Thanks for you time! Don't listen to the dog, it has no idea what it says :)

**Comment by vassilevsky** [comment]
I think that this problem will be better solved by exceptions. I would add a wrapper around the request method. Inside the wrapper, I would check if the response contains errors. If so, I would raise an exception. The exception can be rescued and processed at higher levels. This way, no extra check will be necessary. Could you try this approach in a different branch? Thanks!

**Comment by texpert** [comment]
Actually, I tend to avoid the exceptions when possible - they are much slower and does not add to the code readability.

**Comment by texpert** [comment]
@vassilevsky , so what about doing it without exceptions?

**Comment by texpert** [comment]
@vassilevsky , I have rebased this PR onto develop branch. Could this be merged, please?

**Comment by vassilevsky** [comment]
I've added primitive error handling myself. Thank you for your contribution.

**Pull request closed without merging**
